imac

diff --git a/scripts/dic b/scripts/dic
--- a/scripts/dic
+++ b/scripts/dic
@@ -1,96 +1,134 @@
 #!/bin/bash
+daum="https://dic.daum.net/search.do?q"
+daum_id="https://dic.daum.net/word/view.do?wordid" #=ekw000146827
+daum_tts="https://tts-dic.daum.net/read?lang=en&txt" #=
 
-daum='https://dic.daum.net/search.do?q'
-daum_id='https://dic.daum.net/word/view.do?wordid' #=ekw000146827
+audio_dir=~/Project/dic/mp3
+all_audios=${audio_dir}/*.mp3
 
-dic_dir=~/Project/dic/mp3
-all_audios=${dic_dir}/*.mp3
-
-function trimArg(){
-    W1=${1%%.*}
-    W2=${W1##*/}
-
-    W3=${W2%%-*}
-    W4=${W3%%_*}
-
-    W=$( ./getWID.sh $W4 )
-    WD=${W##*>}
-    WID=${WD%%>*}
+function trimVoice(){
+  sed -E -e '/\+/{s/.*_(.+)\.mp3$/\1/}'\
+    -e '/\+/!{s/.*\/([^_]+)_.*/\1/}' <<< $1
+}
+function urlEncoding(){
+  sed -E -e '/%27/{s//'"'"'/g}'\
+         -e '/%3A/{s//:/g}'\
+         -e '/%2C/{s//,/g}'\
+         -e 's/\+/ /g' <<< $1
+}
+function checkSpell(){
+    sed -En -e '/link_speller/{s/>([^<]+)<|./\1/g;p;q}' \
+        -e '/wordid/!b;s/wordid=([^"]+)"|(>[^<]+)<|./\1\2/g;p;q' \
+        <<< $1
 }
 
-function main(){
-
-
-trimArg $1
-
-if [[ ${WD} != ${1} ]] 
-  then clear; echo "=== Did you mean ${WD}, can't find the ${W1} ===";sleep 2
-fi
-
-  wd_audio=${dic_dir}/${W2}.mp3
-
-  if [[ -z ${1} ]]; then playall 
-  elif [[ -f ${wd_audio} ]]; then printDic ${wd_audio}
-    for i in {1..5}; do mpv ${wd_audio} > /dev/null 2>&1 ; sleep 1; done
-
-    for i in ${all_audios} 
-      do
-        echo -e "$i"
-        mpv "${i}" > /dev/null 2>&1
-        sleep 1
-        echo -e "===>\\t ${W2} \\t<==="
-        mpv "${i}" > /dev/null 2>&1
-        sleep 1
-        mpv "${i}" > /dev/null 2>&1
-        echo -e "${i}"
-        sleep 1
-        clear
-      done
-  else
-    printDic $1
-
-  fi
+function getDaum(){
+    curl -s -A 'Mozilla/4.0' "${daum}=$1"
 }
 
-function getWord(){
-  curl -s -A 'Mozilla/4.0' "${daum}=${W4}" |\
-  sed -En '/wordid/!b;p;q' |\
-  sed -E 's/>([^<]+)<|./\1/g'
+function getWid(){
+  local A1=${1%%.*}
+  local A2=${A1##*/}
+
+  local A3=${A2%%_*}
+  local A4=${A3%%-*}
+
+    res=$( checkSpell "$( getDaum ${A4} )" )
+
+    if [[ "$res" =~ '>' ]]
+      then echo $res
+      else checkSpell "$( getDaum $res )"
+    fi
 }
 
-function printDic(){
-    trimArg $1
-    echo "####### ${W2} #######" 
+function showDicWithWID(){
+    setVAR $1
+    clear
+    echo -e "======== ${WD} == ${exist} ======"
+    curl -s -A 'Mozilla/4.0' "${daum_id}=${WID}"\
+      |sed -En -e '/num_mean/{s/>([^<]+)<|./\1/g;s/[0-9]\.[^0-9]+/\n&/g;s/\.\s+/. /g;bX}'\
+            -e '/inner_tit/{s/.*>([^<]+)<.*/\n<<< \1 >>>/;bX}'\
+            -e '/tit_sort/{s/.*>([^>]+)<.*/\n\t<< \1 >>/g;bX}'\
+            -e '/txt_sort/{s/.*>([^<]+)<.*>([^<]+)<.*/    \1 => \2/g;bX}'\
+            -e '/"tit_word"/{s/.*>\s?([^<]+)<.*/\n\t<< \1 >>\n/;bX}'\
+            -e '/"txt_emph1"/{s/>([^<]+)<|./\1/g;s/.*/ &/;bX}'\
+            -e '/"mean_info"/{s/>([^<]+)<|./\1/g;s/.*/  &\n/;bX}'\
+            -e '/data-audio data-url="http/{s/data-url="([^"]+)"|./\1/g;bX}'\
+            -e 'b'\
+            -e ':X p'
 
-    curl -s -A 'Mozilla/4.0' "${daum_id}=${WID}" |\
-    sed -En '/완료/,/영영사전 더보기/{s/완료/'"${WD}"'/;p}'|\
-    sed -E 's/>([^<]+)<|./\1/g' |\
-    sed -En '/^\S/p' |\
-    sed -En '
-        $!N
+    echo "================ END ==================="
+}
 
-        /^[^0-9]/ { /\n[0-9]/ bX}
-        /^[0-9]/  { /\n[0-9]/ bX}
-        /^[0-9]/  { /\n[^0-9]/bX}
+function playdic(){
 
-        bY
-        :X
-        s/^[0-9].*/\t&/
-        P
-        D
+            awk -v sfile=${2} -v exist=${3} 'BEGIN{FNAME; I;}
 
-        :Y 
-        D
-        '
+            {if($0 ~ /http/) {
+                    if(/&format/){\
+                      FNAME = gensub(/.*en&*txt=([^&.]+).*/,sfile"_\\1.mp3","1")
+                      #print FNAME
+                    }else {
+                      FNAME = sfile"_"(I++)".mp3"
+                      #print FNAME
+                    }
+                    
+                      if(exist=="New"){
+                        cmd_curl="xargs -I{} curl -o "FNAME" {} > /dev/null 2>&1" 
+                        print $0 | cmd_curl
+                        close(cmd_curl)
+                        print "curl downloading... "
+                      }
+                      cmd_mpv="mpv "FNAME" > /dev/null 2>&1"
+                      print $0 | cmd_mpv 
+                      close (cmd_mpv)
+                }else  print $0
 
-    echo "======= END of $WD ==================="
-
+              print "sleep 1" | "/bin/bash"
+              close("/bin/bash")
+            }' <<< $1
 }
 
 function playall(){
-  for i in ${all_audios}; do echo ${i}; mpv ${i} > /dev/null 2>&1;  sleep 1; mpv ${i} > /dev/null 2>&1; sleep 1; mpv ${i} > /dev/null 2>&1; done
+  [[ ${1} != '' ]] && v1=${1/%/_0} || v1="*_0"
+
+  for i in ${audio_dir}/${v1}.mp3
+    do 
+        showDicWithWID "$( getWid $i )"
+        for j in ${i/0/*}
+          do  
+              #urlEncoding $(trimVoice $j)
+              mpv $j > /dev/null 2>&1
+              sleep 1
+          done
+    done
+
 }
 
-#####################
-main $1
+function setVAR(){
+  W1=${1%%.*}
+  W2=${W1##*/}
 
+  W3=${W2%%_*}
+  W4=${W3%%-*}
+
+  W="$( getWid $W4 )"
+  WD=${W##*>}
+  WID=${W%%>*}
+  sfile=${audio_dir}/${WD}
+  exist=""
+  [[ -f ${sfile}_0.mp3 ]] && exist=Old || exist=New
+}
+
+function mainDic(){
+  setVAR $1
+  clear
+
+  if [[ ${WD} != ${W4} ]] 
+    then clear; echo "=== Did you mean ${WD}, can't find the ${W4} ===";sleep 2
+  fi
+    playdic "$( showDicWithWID $1 )" ${sfile} ${exist}
+}
+
+setVAR $1
+[[ -f ${sfile}_0.mp3 ]] && playall || ( mainDic $1 )
